In [29]:
import pandas as pd
import numpy as np
import random
#from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [30]:
urls_data=pd.read_csv("urldata.csv")

In [31]:
type(urls_data)

pandas.core.frame.DataFrame

In [32]:
urls_data.head()

                      url label
0  diaryofagameaddict.com   bad
1        espdesign.com.au   bad
2      iamagameaddict.com   bad
3           kalantzis.net   bad
4   slightlyoffcenter.net   bad

In [33]:
def makeTokens(f):
    tkns_BySlash=str(f.encode('utf-8')).split('/')
    total_Tokens=[]
    for i in tkns_BySlash:
        tokens=str(i).split('-')
        tkns_ByDot=[]
        for j in range(0,len(tokens)):
            temp_Tokens=str(tokens[j]).split('-')
            tkns_ByDot=tkns_ByDot+temp_Tokens
            total_Tokens=total_Tokens+tokens+tkns_ByDot
            total_Tokens=list(set(total_Tokens))
    if 'com' in total_Tokens:
        total_Tokens.remove('com')
    return  total_Tokens

In [34]:
y=urls_data["label"]

In [35]:
url_list=urls_data["url"]

In [36]:
vectorizer=TfidfVectorizer(tokenizer=makeTokens)

In [40]:
X=vectorizer.fit_transform(url_list)